### ISSUE TITLE
Compile error: User-defined type not defines

### ISSUE THREAD

**Issue by marza91** [kjnh10/ExcelLikeVim#1]
Hello,

Decided to give this a try since I've started wanting keybindings for everything, but there seems to be a problem when I first click a button (h,j,k or l) after installing and starting up:

> Compile error:
> User-defined type not defined

I've never worked with scripts like these before, but the error is happening in keyStrokeAsseser, on this line (can't fint a way to show line numbers):

`Private Function NumberOfHits(stroke As String, context, modeOfVim) As Long '{{{`

I didn't manage to find out exactly which type it disliked, but I would be happy to help trying to find out.

Some info:
Excel version: Microsoft Excel 2016 MSO (16.0.8730.2046) 32-bit
Office version: MS Office Professional Plus 2016
Windows: Windows 10 version 1709 (OS Build: 17025.1000)

Also, I managed to finally find the Stact Trace with some more debug info, but I'm not sure how much it helps really:

![2017_12_18_14_42_34](https://user-images.githubusercontent.com/1224973/34109201-21a59406-e403-11e7-8559-a8245384ed62.png)

**Comment by marza91** [comment]
Quick update: The issue seems to be "LongLong" which is not defined on my computer. Maybe I'm missing something?

**Comment by kojinho10** [comment]
Hi marza91,

Thanks for your try and reporting the issue.

Maybe your issue will be resolved if you delete the line below in keystrokeasseser module.
#889 Dim s As LongLong

I'm now checking more detail and am going to release the new fixed version later.

**Comment by marza91** [comment]
Sorry for taking so long with this, haven't been able to test at a computer during the holidays..

I tried to remove the "LongLong" from files, but it doesn't seem to change anything for the xlam file. I haven't worked with Excel plugins before, do I have to re-compile it or something like that? I tried to google but having ha hard time finding how to do this.

**Comment by kojinho10** [comment]
Sorry for my late reply.
I was a little bit busy last week.

The reason that your modification didn't affect is this xlam file will load .bas files only when pressing F3 in excel.

Anyway, I have fixed this issue in the latest commit, 
so could you try to download the latest commit like below?
`git clone https://github.com/kojinho10/ExcelLikeVim.git`

**Comment by marza91** [comment]
Working great now, thanks!
