### ISSUE TITLE
Plugin is not working for Microsoft Excel 2010 on Windows 7 Enterprise

### ISSUE THREAD

**Issue by Zhu-Justin** [kjnh10/ExcelLikeVim#10]
I installed the vimx plugin (it shows up under Options > Plugins) and tried the following:
1. Enable Trust Center Logging under Options > Trust Center
2. Set Microsoft DAO 3.6 Object Library under Tools > References under Microsoft Office VBA

When I press 'j', I simply edit the contents of the cell to be 'j' rather than move down a cell.

Could you look into fixing this issue?  Much thanks for the help

**Comment by kjnh10** [comment]
Did you check 'Trust access to the VBA project object model'

Maybe you can navigate there by
Security center -> macro setting >  'Trust access to the VBA project object model'

**Comment by Zhu-Justin** [comment]
Yes, I have also enabled Macro Settings > Trust access to the VBA project object model

**Comment by kjnh10** [comment]
uhhh....

Could you check off the Microsoft DAO 3.6 Object Library since it's for older versions of EXCEL?

**Comment by kjnh10** [comment]
Or could you check that vim.xlam recognized correctly like below?

![image](https://user-images.githubusercontent.com/6933428/62586771-fc410d80-b8f9-11e9-9e6a-2279ca817e52.png)

**Comment by kjnh10** [comment]
I will close.

If you have any, please reopen.
