### ISSUE TITLE
Cannot get pressing F3 to activate the add-in

### ISSUE THREAD

**Issue by Ouilly** [kjnh10/ExcelLikeVim#16]
Hi kjnh10,

Love the plugin!

I have an issue when initiating/activating the plugin. I cannot get pressing F3 to work. I have to re-add the add-in from the "Add-ins" menu each time I want to use it. It then asks me if I wish to replace the file (with the same file) and then, once i have pressed yes, it works like a charm. Let me know if you want to see any screenshots or outputs, I am happy to provide them.

This could be a me-problem but any help is appreciated as I absolutely adore this add-in as a vim-user and occasional excel-user!

All the best,
Ouilly

**Comment by kjnh10** [comment]
Thanks for reporting.

Could you paste screenshots or outputs?
And please tell me about your Excel version.

Thanks,

**Comment by Ouilly** [comment]
Hi again,

Not sure if this is useful but here are a few screenshots showing the process i go through to work around the problem in roughly the following steps:

1. Opening Visual Basic in an empty spreadsheet without pressing any buttons
2. Pressing F3 and then attempting navigating using 'j' and 'k'
3. Navigating to Excel Add-ins
4. Re-adding the add-in using 'Browse'
5. Confirming the replacement of the file, once chosen
6. Navigating with 'j' and 'k' etc. now works
7. Visual Basic after the add-in has been re-added

![Step 1 - opening visual basic](https://user-images.githubusercontent.com/88192307/185924510-786e9153-f162-49f3-a6f3-9fdd2d0550f1.jpg)
![Step 2 - attempt to navigate after pressing F3](https://user-images.githubusercontent.com/88192307/185924512-71ba0a66-5cc8-466d-bdb4-6e21799e74a8.jpg)
![Step 3 - navigating to 'Excel Add-ins' under 'Developer'](https://user-images.githubusercontent.com/88192307/185924514-4cfe79ae-df38-4f09-8b0a-fd872b74fdae.jpg)
![Step 4 - 'Browse' navigating to existing plugin and re-adding](https://user-images.githubusercontent.com/88192307/185924516-1213adc4-1edd-4afe-a692-aeeeaa5b66dd.jpg)
![Step 5 - replacing existing vimx-xlam](https://user-images.githubusercontent.com/88192307/185924522-156f0ab7-c272-4490-8a26-71346e1b71d8.jpg)
![Step 6 - pressing 'j'](https://user-images.githubusercontent.com/88192307/185924506-1dae500c-b00e-4fbf-bba0-a71cb8a8a474.jpg)
![Step 7 - Visual Basic after re-adding add-in](https://user-images.githubusercontent.com/88192307/185924509-7f42492c-0147-41ad-a84b-5fa30217d9bb.jpg)

My Excel version is: Microsoft® Excel® for Microsoft 365 MSO (Version 2207 Build 16.0.15427.20182) 64-bit

Not quite sure how to properly show this issue and perhaps only the final image with the Visual Basic output is of any use; however, I hope you have what you need for now at least. Please let me know if you want more pictures or outputs!

Best,
Ouilly

**Comment by kjnh10** [comment]
Thanks for the explanation.
I would like to confirm you just want to start using excel, and for that purpose, you pressed F3. Right?
If it's so, you don't need to press F3.

You can just press ctrl + n to open a new book or open some files from the menu bar.

**Comment by kjnh10** [comment]
Pressing F3 is for reloading this libarary when you modify the code which are stored in .vb files.

And F3 should not be pressed in the VBA editor, since this tool can't handle the pressed keys in the VBA editor.
