### ISSUE TITLE
insert mode (i or a) doesn't work

### ISSUE THREAD

**Issue by anyfactor** [kjnh10/ExcelLikeVim#6]

**Comment by kjnh10** [comment]
Hi, anyfactor,
Could you provide some more details for your scenario?

**Comment by anyfactor** [comment]
Navigation keys (```hjkl```) and other stuffs works but inserting a cell does not work. Double clicking a cell puts me in insert mode. But pressing ```i``` or ```a``` does not enables insert mode.  And is it possible for excel to retain its own shortcuts also like ```ctrl + z```?

**Comment by kjnh10** [comment]
Sorry, I fixed the problem.

Could you try the new version below?
https://github.com/kjnh10/ExcelLikeVim/releases/tag/v2.3.3

At first, please note that you need to remove the version you installed to excel.


>And is it possible for excel to retain its own shortcuts also like ctrl + z?

You can set this in your setting file `<your_HOME_folder>/vimx/user_configure.bas`

The setting will be something like below.
```
Attribute VB_Name = "user_configure"

Public Sub init()
  Application.Cursor = xlNorthwestArrow
  Call keystrokeAsseser.init  'needed
  call vimize.main   'needed
  call mykeymap  'you need to define below
End Sub 

private sub mykeymap()
  'You can exclude any keys from this software and use them for excel default feature like {^f} => search.
  Application.OnKey "^{f}" 
  Application.OnKey "^{a}"
  Application.OnKey "^{c}"
  Application.OnKey "^{n}"
  Application.OnKey "^{p}"
  Application.OnKey "^{s}"
  Application.OnKey "^{v}"
  Application.OnKey "^{w}"
  Application.OnKey "^{x}"
  Application.OnKey "^{z}"
  Application.OnKey "{F2}"
  Application.OnKey "{F11}"
  Application.OnKey "{F12}"

  Call nmap("c", "<vba function>")   ' key c => call <vba function>
  Call nmap("bb", "<vba function2>")  'key bb => call <vba function2>
end sub
```
You can also see my more detailed setting in README. :)

**Comment by anyfactor** [comment]
Thanks, it works!!
