### ISSUE TITLE
Does not work in Excel 2013

### ISSUE THREAD

**Issue by ptendolkar** [kjnh10/ExcelLikeVim#8]
Downloaded the latest release (2.3.3). Trused VBA programs as stated in installation. I now see it listed in Add-Ins section of Options panel. The functionality has not changed; hjkl would simply add 'hjkl' to the currently selected cell. I was never able to get this to work. I do not see any error pop up either, but I am not sure how to troubleshoot since I'm not familiar with excel add-ins.

**Comment by kjnh10** [comment]
verry sorry for late replay.

I think this is not the excel 2013 version issue, becuase in my environment 2010 and 2016 are working fine.

can you check this addin recognized from excel application like below?
![image](https://user-images.githubusercontent.com/6933428/52158848-64394180-2694-11e9-9449-1d55b60c3564.png)

**Comment by wiky2** [comment]
pls try to turn your input method to English.

**Comment by kjnh10** [comment]
@wiky2 
What did you mean by 'input method'?
language for comments in the code?
If so, I will try.

**Comment by wiky2** [comment]
@kjnh10
I've got used to this. When I begin to use Vim mode , I would turn my inputting language from Chinese to English. But maybe it is not the same thing with @ptendolkar

**Comment by kjnh10** [comment]
I close this.
@ptendolkar , if you need, reopen.
